export const saleTabs = [
  { href: '/sales', label: '概要' },
  { href: '/sales/revenue', label: '売上集計' },
  { href: '/sales/slips', label: '伝票一覧' },
  { href: '/sales/new-existing', label: '新規/既存' },
  { href: '/sales/roas', label: 'ROAS' },
  { href: '/sales/ad-costs', label: '広告費入力' },
  { href: '/sales/ltv', label: 'LTV' },
  { href: '/sales/repeat', label: 'リピート' },
  { href: '/sales/hourly', label: '時間単価' },
  { href: '/sales/utilization', label: '稼働率' },
  { href: '/sales/cross', label: 'クロス集計' },
  { href: '/sales/area-ltv', label: 'エリア分析' },
  { href: '/sales/map', label: '地域分布' },
]
